# Generated by Django 3.2.6 on 2021-08-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_produto', models.CharField(max_length=30)),
                ('quantidade', models.CharField(max_length=3)),
                ('preco', models.CharField(max_length=7)),
            ],
        ),
    ]
