# Generated by Django 3.2.6 on 2021-09-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_uti', '0002_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='entrada_e_saida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now=True)),
                ('venda_servico', models.CharField(max_length=10)),
                ('n_da_os', models.CharField(max_length=10)),
                ('descricao', models.TextField()),
                ('saida', models.CharField(max_length=6)),
                ('entrada', models.CharField(max_length=6)),
                ('forma_de_pagamento', models.CharField(max_length=15)),
                ('parcelas', models.CharField(max_length=2)),
                ('codigo_de_barras', models.CharField(max_length=13)),
                ('observacao', models.TextField()),
            ],
        ),
    ]
