# Generated by Django 3.2.6 on 2021-09-25 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_uti', '0003_entrada_e_saida'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='codigo_de_barras',
            field=models.CharField(default=1234567894658, max_length=13),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entrada_e_saida',
            name='data',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='entrada_e_saida',
            name='forma_de_pagamento',
            field=models.CharField(choices=[('D', 'DÉBITO'), ('C', 'CRÉDITO'), ('DN', 'DINHEIRO'), ('P', 'PIX')], max_length=15),
        ),
        migrations.AlterField(
            model_name='entrada_e_saida',
            name='n_da_os',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='entrada_e_saida',
            name='parcelas',
            field=models.CharField(choices=[('AV', 'Á VISTA'), ('2', '2x'), ('3', '3x')], max_length=2),
        ),
        migrations.AlterField(
            model_name='entrada_e_saida',
            name='venda_servico',
            field=models.CharField(choices=[('V', 'VENDA'), ('S', 'SERVIÇO')], max_length=1),
        ),
    ]
